openapi: 3.2.0
info:
  version: 2016-04-18
  x-release: v4
  title: 'Amazon Cognito Identity Provider #X Amz Target=AWSCognitoIdentityProviderService.GetUICustomization API'
  description: <p>Using the Amazon Cognito user pools API, you can create a user pool to manage directories and users. You can authenticate a user to obtain tokens related to user identity and access policies.</p> <p>This API reference provides information about user pools in Amazon Cognito user pools.</p> <p>For more information, see the <a href="https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html">Amazon Cognito Documentation</a>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: cognito-idp
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/cognito-idp-2016-04-18.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://cognito-idp.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Cognito Identity Provider multi-region endpoint
- url: https://cognito-idp.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Cognito Identity Provider multi-region endpoint
- url: http://cognito-idp.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Cognito Identity Provider endpoint for China (Beijing) and China (Ningxia)
- url: https://cognito-idp.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Cognito Identity Provider endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSCognitoIdentityProviderService.GetUICustomization'
paths:
  /#X-Amz-Target=AWSCognitoIdentityProviderService.GetUICustomization:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetUICustomization
      description: Gets the user interface (UI) Customization information for a particular app client's app UI, if any such information exists for the client. If nothing is set for the particular client, but there is an existing pool level customization (the app <code>clientId</code> is <code>ALL</code>), then that information is returned. If nothing is present, then an empty shape is returned.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUICustomizationResponse'
              examples:
                GetUICustomization200Example:
                  summary: Default GetUICustomization 200 response
                  x-microcks-default: true
                  value:
                    UICustomization: example-value
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
              examples:
                GetUICustomization480Example:
                  summary: Default GetUICustomization 480 response
                  x-microcks-default: true
                  value: example
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                GetUICustomization481Example:
                  summary: Default GetUICustomization 481 response
                  x-microcks-default: true
                  value: example
        '482':
          description: NotAuthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotAuthorizedException'
              examples:
                GetUICustomization482Example:
                  summary: Default GetUICustomization 482 response
                  x-microcks-default: true
                  value: example
        '483':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                GetUICustomization483Example:
                  summary: Default GetUICustomization 483 response
                  x-microcks-default: true
                  value: example
        '484':
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorException'
              examples:
                GetUICustomization484Example:
                  summary: Default GetUICustomization 484 response
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUICustomizationRequest'
            examples:
              GetUICustomizationRequestExample:
                summary: Default GetUICustomization request
                x-microcks-default: true
                value:
                  UserPoolId: us-east-1_AbCdEfGhI
                  ClientId: us-east-1_AbCdEfGhI
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSCognitoIdentityProviderService.GetUICustomization
      summary: Amazon Cognito Get U I Customization
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSCognitoIdentityProviderService.GetUICustomization'
components:
  schemas:
    ResourceNotFoundException: {}
    UserPoolIdType:
      type: string
      pattern: '[\w-]+_[0-9a-zA-Z]+'
      minLength: 1
      maxLength: 55
    UICustomizationType:
      type: object
      properties:
        UserPoolId:
          allOf:
          - $ref: '#/components/schemas/UserPoolIdType'
          - description: The user pool ID for the user pool.
        ClientId:
          allOf:
          - $ref: '#/components/schemas/ClientIdType'
          - description: The client ID for the client app.
        ImageUrl:
          allOf:
          - $ref: '#/components/schemas/ImageUrlType'
          - description: The logo image for the UI customization.
        CSS:
          allOf:
          - $ref: '#/components/schemas/CSSType'
          - description: The CSS values in the UI customization.
        CSSVersion:
          allOf:
          - $ref: '#/components/schemas/CSSVersionType'
          - description: The CSS version number.
        LastModifiedDate:
          allOf:
          - $ref: '#/components/schemas/DateType'
          - description: The last-modified date for the UI customization.
        CreationDate:
          allOf:
          - $ref: '#/components/schemas/DateType'
          - description: The creation date for the UI customization.
      description: A container for the UI customization information for a user pool's built-in app UI.
    GetUICustomizationResponse:
      type: object
      required:
      - UICustomization
      properties:
        UICustomization:
          allOf:
          - $ref: '#/components/schemas/UICustomizationType'
          - description: The UI customization information.
    GetUICustomizationRequest:
      type: object
      required:
      - UserPoolId
      title: GetUICustomizationRequest
      properties:
        UserPoolId:
          allOf:
          - $ref: '#/components/schemas/UserPoolIdType'
          - description: The user pool ID for the user pool.
        ClientId:
          allOf:
          - $ref: '#/components/schemas/ClientIdType'
          - description: The client ID for the client app.
    ClientIdType:
      type: string
      pattern: '[\w+]+'
      minLength: 1
      maxLength: 128
      format: password
    NotAuthorizedException: {}
    DateType:
      type: string
      format: date-time
    CSSVersionType:
      type: string
    CSSType:
      type: string
    TooManyRequestsException: {}
    ImageUrlType:
      type: string
    InvalidParameterException: {}
    InternalErrorException: {}
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/cognito-idp/
x-hasEquivalentPaths: true
