openapi: 3.0.0
info:
  version: 2014-06-30
  x-release: v4
  title: 'Amazon Cognito Identity #X Amz Target=AWSCognitoIdentityProviderService.AddCustomAttributes #X Amz Target=AWSCognitoIdentityProviderService.AddCustomAttributes #X Amz Target=AWSCognitoIdentityProviderService.ListResourceServers API'
  description: <fullname>Amazon Cognito Federated Identities</fullname> <p>Amazon Cognito Federated Identities is a web service that delivers scoped temporary credentials to mobile devices and other untrusted environments. It uniquely identifies a device and supplies the user with a consistent identity over the lifetime of an application.</p> <p>Using Amazon Cognito Federated Identities, you can enable authentication with one or more third-party identity providers (Facebook, Google, or Login with Amazon) or an Amazon Cognito user pool, and you can also choose to support unauthenticated access from your app. Cognito delivers a unique identifier for each user and acts as an OpenID token provider trusted by AWS Security Token Service (STS) to access temporary, limited-privilege AWS credentials.</p> <p>For a description of the authentication flow from the Amazon Cognito Developer Guide see <a href="https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html">Authentication Flow</a>.</p> <p>For more information see <a href="https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html">Amazon Cognito Federated Identities</a>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: cognito-identity
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/cognito-identity-2014-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://cognito-identity.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Cognito Identity multi-region endpoint
- url: https://cognito-identity.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Cognito Identity multi-region endpoint
- url: http://cognito-identity.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Cognito Identity endpoint for China (Beijing) and China (Ningxia)
- url: https://cognito-identity.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Cognito Identity endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSCognitoIdentityProviderService.ListResourceServers'
paths:
  /#X-Amz-Target=AWSCognitoIdentityProviderService.ListResourceServers:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListResourceServers
      description: Lists the resource servers for a user pool.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResourceServersResponse'
              examples:
                ListResourceServers200Example:
                  summary: Default ListResourceServers 200 response
                  x-microcks-default: true
                  value:
                    ResourceServers: example-value
                    NextToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
              examples:
                ListResourceServers480Example:
                  summary: Default ListResourceServers 480 response
                  x-microcks-default: true
                  value: example
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListResourceServers481Example:
                  summary: Default ListResourceServers 481 response
                  x-microcks-default: true
                  value: example
        '482':
          description: NotAuthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotAuthorizedException'
              examples:
                ListResourceServers482Example:
                  summary: Default ListResourceServers 482 response
                  x-microcks-default: true
                  value: example
        '483':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ListResourceServers483Example:
                  summary: Default ListResourceServers 483 response
                  x-microcks-default: true
                  value: example
        '484':
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorException'
              examples:
                ListResourceServers484Example:
                  summary: Default ListResourceServers 484 response
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListResourceServersRequest'
            examples:
              ListResourceServersRequestExample:
                summary: Default ListResourceServers request
                x-microcks-default: true
                value:
                  UserPoolId: us-east-1_AbCdEfGhI
                  MaxResults: example-value
                  NextToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSCognitoIdentityProviderService.ListResourceServers
      summary: Amazon Cognito List Resource Servers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSCognitoIdentityProviderService.ListResourceServers'
components:
  schemas:
    ResourceNotFoundException: {}
    ResourceServerScopeDescriptionType:
      type: string
      minLength: 1
      maxLength: 256
    ResourceServersListType:
      type: array
      items:
        $ref: '#/components/schemas/ResourceServerType'
    ResourceServerNameType:
      type: string
      pattern: '[\w\s+=,.@-]+'
      minLength: 1
      maxLength: 256
    InvalidParameterException: {}
    PaginationKeyType:
      type: string
      pattern: '[\S]+'
      minLength: 1
    TooManyRequestsException: {}
    InternalErrorException: {}
    ResourceServerType:
      type: object
      properties:
        UserPoolId:
          allOf:
          - $ref: '#/components/schemas/UserPoolIdType'
          - description: The user pool ID for the user pool that hosts the resource server.
        Identifier:
          allOf:
          - $ref: '#/components/schemas/ResourceServerIdentifierType'
          - description: The identifier for the resource server.
        Name:
          allOf:
          - $ref: '#/components/schemas/ResourceServerNameType'
          - description: The name of the resource server.
        Scopes:
          allOf:
          - $ref: '#/components/schemas/ResourceServerScopeListType'
          - description: A list of scopes that are defined for the resource server.
      description: A container for information about a resource server for a user pool.
    NotAuthorizedException: {}
    ResourceServerScopeListType:
      type: array
      items:
        $ref: '#/components/schemas/ResourceServerScopeType'
      maxItems: 100
    ResourceServerIdentifierType:
      type: string
      pattern: '[\x21\x23-\x5B\x5D-\x7E]+'
      minLength: 1
      maxLength: 256
    ListResourceServersRequest:
      type: object
      required:
      - UserPoolId
      title: ListResourceServersRequest
      properties:
        UserPoolId:
          allOf:
          - $ref: '#/components/schemas/UserPoolIdType'
          - description: The user pool ID for the user pool.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/ListResourceServersLimitType'
          - description: The maximum number of resource servers to return.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationKeyType'
          - description: A pagination token.
    ListResourceServersLimitType:
      type: integer
      minimum: 1
      maximum: 50
    ResourceServerScopeNameType:
      type: string
      pattern: '[\x21\x23-\x2E\x30-\x5B\x5D-\x7E]+'
      minLength: 1
      maxLength: 256
    ResourceServerScopeType:
      type: object
      required:
      - ScopeName
      - ScopeDescription
      properties:
        ScopeName:
          allOf:
          - $ref: '#/components/schemas/ResourceServerScopeNameType'
          - description: The name of the scope.
        ScopeDescription:
          allOf:
          - $ref: '#/components/schemas/ResourceServerScopeDescriptionType'
          - description: A description of the scope.
      description: A resource server scope.
    UserPoolIdType:
      type: string
      pattern: '[\w-]+_[0-9a-zA-Z]+'
      minLength: 1
      maxLength: 55
    ListResourceServersResponse:
      type: object
      required:
      - ResourceServers
      properties:
        ResourceServers:
          allOf:
          - $ref: '#/components/schemas/ResourceServersListType'
          - description: The resource servers.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationKeyType'
          - description: A pagination token.
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/cognito-identity/
x-hasEquivalentPaths: true
